
update
upgrade

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed

install findutils

install bash

tap homebrew/dupes
install homebrew/dupes/grep

tap railwaycat/emacsmacport
install emacs-mac

install zsh
install ack
install git
install tree
install hub
install python
install heroku-toolbelt
install erlang
install redis
install riak
install wget

# Install homebrew-cask

tap phinze/homebrew-cask
install brew-cask

# Install osx apps

cask --appdir="/Applications" \
  alfred \
  dropbox \
  google-drive \
  one-password \
  iterm2 \
  nv-alt \
  spotify \
  slate \
  sublime-text

# Remove outdated versions from the cellar

cleanup
