#!/bin/sh

# Check for Homebrew

if test ! $(which brew); then
  echo "installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
fi

brew bundle $DOTFILES/brew/Brewfile

