#!/bin/sh

# Check for Homebrew

if test ! $(which brew); then
  echo "installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew bundle $DOTFILES/brew/Brewfile

